### ISSUE TITLE
Change docs workfow to actually build the documentation

### ISSUE THREAD

**Issue by ABohynDOE** [DOE-police/DOEDA#21]
I think that for now the workflow takes the built documentation in `docs/build/html`  and moves it to the `gh-pages` branch.
https://github.com/DOE-police/DOEDA/blob/40e2537e51ad5941c6f34de585c1ece8e7e5c6bb/.github/workflows/merge-master.yml#L19
But this means that everytime I change something in the documentation, I have to rebuild the whole doccs as html and push it as a commit (~20 files) which is cumbersome.
What I would like to do is add the `docs/build` folder to `.gitignore` and then have the workflow build the actual documentation from `docs/source` before copying it to `gh-pages`.

**Comment by ABohynDOE** [comment]
For now, the way I build the documentation is by running `make html` in the `docs/` folder (the one that contains the makefile).
So I guess there should be a way of integrating that into the workflow ?

**Comment by dmbarreiro** [comment]
Sure, that's the right way to do it. I'll change the workflow to do that
